### ISSUE TITLE
Add effective dates to Service Alerts

### ISSUE THREAD

**Issue by msrichardson** [ibi-group/trimet-mod-otp#136]
Please add the effective date to the end of each service alert (see below for examples).  [The effective start date is included in the OTP response.]

![croppercapture 332](https://user-images.githubusercontent.com/4853348/47533017-f399b200-d866-11e8-8d58-ccfb215a0e9f.png)

**Comment by landonreed** [comment]
The "Effective as of" text was added some time ago. However, a continuation of this issue is that @msrichardson has found cases where the string reads `Effective as of Last Tuesday` rather than simply using the calendar format.

The source appears to be an incorrect use of moment here:

https://github.com/opentripplanner/otp-react-redux/blob/13061968d9cdb18fae34e545a2ebce8ac72d803d/lib/components/narrative/line-itin/transit-leg-body.js#L212-L217
