### ISSUE TITLE
OTP leg output

### ISSUE THREAD

**Issue by msrichardson** [ibi-group/trimet-mod-otp#212]
Time v distance calculations seem to be off for some legs of some trips (have not yet found a pattern).

See second walk leg for the first link, and first scooter leg for the second (especially as compared to the second one, which is the same distance).

Per Evan, "Something is wrong with outputting the legs from OTP.  There are a lot of leg steps missing in the response from OTP."

https://trimet-mod-dev.ibi-transit.com/#/?ui_activeSearch=nc2y6prw8&ui_activeItinerary=0&fromPlace=737%20SW%20Salmon%20St%2C%20Portland%2C%20OR%2C%20USA%2097205%3A%3A45.51771462144638%2C-122.68166539329073&toPlace=1839%20SE%2045th%20Ave%2C%20Portland%2C%20OR%2C%20USA%2097215%3A%3A45.50959505548101%2C-122.61626142378594&date=2019-07-03&time=12%3A52&arriveBy=false&mode=BUS%2CTRAM%2CRAIL%2CGONDOLA%2CMICROMOBILITY_RENT&showIntermediateStops=true&optimize=QUICK&maxWalkDistance=4828&maxEScooterDistance=4828&ignoreRealtimeUpdates=true&companies=BOLT%2CCLEVR%2CLIME%2CRAZOR%2CSHARED%2CSPIN

https://trimet-mod-dev.ibi-transit.com/#/?ui_activeSearch=049hnq2dr&ui_activeItinerary=0&fromPlace=1221%20NW%20Everett%20St%2C%20Portland%2C%20OR%2C%20USA%2097209%3A%3A45.52505074007402%2C-122.68372405582535&toPlace=1839%20SE%2045th%20Ave%2C%20Portland%2C%20OR%2C%20USA%2097215%3A%3A45.50959505548101%2C-122.61626142378594&date=2019-07-03&time=12%3A52&arriveBy=false&mode=BUS%2CTRAM%2CRAIL%2CGONDOLA%2CMICROMOBILITY_RENT&showIntermediateStops=true&optimize=QUICK&maxWalkDistance=4828&maxEScooterDistance=4828&ignoreRealtimeUpdates=true&companies=BOLT%2CCLEVR%2CLIME%2CRAZOR%2CSHARED%2CSPIN

**Comment by landonreed** [comment]
@msrichardson, the first link doesn't appear to be showing anything problematic any longer. Can you confirm?

Also, just to be a bit more descriptive here, the underlying issue here is that a walk or scooter leg with a distance of, say, 0.5 miles is being returned with unpredictable durations, which seem to to sometimes take much longer (e.g., 9 minutes on a scooter for the first scooter leg of the second link) than they should. Is that description correct?

**Comment by landonreed** [comment]
The fact that I'm no longer seeing some of these cases leads me to believe that it might be related to opentripplanner/opentripplanner#2790.

**Comment by evansiroky** [comment]
I'll add that another matter at play is the turn costs being added. In the current implementation, each of the edges that get split to insert the eScooters into the graph result in the creation of a new pseudo-intersection that experiences turn delays. Even straight turns have 5 seconds of added turn time added. Over time all these split edges significantly added to the traversal time.

**Comment by msrichardson** [comment]
@landonreed The first link is providing a totally different result now.  Whether it is problematic or not though, sorry, I don't know (is 32 minutes a reasonable duration for a 3.7 mile scooter trip? I honestly don't know the speed, etc set for scooters).

Yes, I was randomly finding both walk and scooter legs where the time duration didn't seem to match the length (usually, if not always, the time duration being much longer than expected).  

I'll try to remember to go back to using screenshots (either alone or in conjunction with links), given our experiences with the first link today.

**Comment by landonreed** [comment]
Yes, I think links + screenshots are probably the best way to document issues in general. We're fairly certain though that this issue is contained to areas where there are a large number of bikeshare/scooter floating vehicles which are interrupting the routing as described in the above comments by me and @evansiroky.

**Comment by landonreed** [comment]
Closing, as this was resolved by the OTP back end fix.
