### ISSUE TITLE
eScooter references in itinerary

### ISSUE THREAD

**Issue by msrichardson** [ibi-group/trimet-mod-otp#213]
As per our discussions in Slack, in the itinerary, please replace the bike_id references with company and append 'eScooter'.  For example, Walk 0.1 miles to Bolt eScooter.

In order to avoid hardcoding anything, create a reference table based on the company, to know whether or not to append 'eScooter' (as not all 'vehicles' in the feed are necessarily scooters).

This would apply to both the walk aspect and the main itinerary 'waypoint'.

![CropperCapture 397](https://user-images.githubusercontent.com/4853348/60624700-d8d6f000-9d9a-11e9-8cfd-3ee8b70f81c0.png)

**Comment by landonreed** [comment]
@msrichardson, I have a couple of clarification questions:
- How should this appear for Biketown? `Walk 75 feet to Biketown bicycle`?
- Does the `Pick up RAZOR vehcile T90T` text need to change?
- We also discussed removing the "floating vehicle" text in the popup for bikes and eScooter markers in the map overlay. What should be the respective text for each of these (instead of `Floating vehicle GBFS 0342 BIKETOWN` and `Floating vehicle LIME LV3MMH6NGGXFT`)?

**Comment by msrichardson** [comment]
@landonreed  Here are a couple of answers:

- I don't believe the "Pick up RAZOR vehicle XYZ" needs to change (but I will verify).  That said, 'vehicle' is misspelled in the example above.  Not sure if that typo is coming from the feed, something behind the scenes, or was just a typo :)

- We are still determining what to do about the Floating Vehicle text.

**Comment by msrichardson** [comment]
@landonreed  Okay, here are the rest of the answers (minus floating vehicle):

- Oops, yes, the "Pick up Scooter Co vehicle XYZ" does need to change.  Sorry about that.  At minimum, leave off the ID; at best, change vehicle to scooter.

- BIKETOWN is fine as is, thanks.  (Ideally, the scooters would show a similar walk to what BIKETOWN and carshare currently do, but I understand that isn't feasible, so the above is the next best solution, so to speak.)
